### ISSUE TITLE
Cached Files for AppVeyor

### ISSUE THREAD

**Issue by mastacheata** [mastacheata/chocolatey-packages#9]
For some reason the nuspec file can't be preserved even if it's defined in cached files.
I suppose this is due to the path already being part of the git root, but the file not being tracked there.
Looks like it overwrites the folder content with the git clone after restoring the cached file.

Will check with AppVeyor support if that's true or if I'm doing something wrong.

**Comment by mastacheata** [comment]
Ok, cached files are only ever cached if the build is successful.
Obviously, though, since implementing the version checks against the chocolatey.org website last weekend, no build has succeeded anymore so far.

Maybe that'll work once the next version is released in a few weeks or so.
Only thing I'm not sure about is the order of restore and git clone.
If it restores the file before cloning the repository, the clone will fail due to a non-empty, already existing target directory.
All I can do about that is wait and see what happens.

**Comment by Spunkie** [comment]
> Ok, cached files are only ever cached if the build is successful.

Oh....... that's useful to know, thanks.
___

It would seem likely to me that appveyor will restore the cache before running anything like git, but I could be wrong. You may want to try saving the data in some other directory than the working directory for builds to be safe. Personally though, I've never really understood what the file system of appveyor looks like other than it being a windows based VM. 

I've not tried this yet but it might be helpful here. You can apparently set the build VM to stay up for 1 hour after a fail and RDP into it to make debugging easier. https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by mastacheata** [comment]
@Spunkie 
I'll look into that tomorrow. Didn't have much time last week,
At least now we know that the AutoDeployment thingy works as it just pushed 2017.3 to chocolatey.org a few minutes ago.
